import Head from 'next/head'
import Image from 'next/image'
import Categories from '../components/Categories'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import PostCard from '../components/PostCard'
import PostWidget from '../components/PostWidget'
import { getPosts } from '../services'

export default function Home({ posts }) {
  return (
    <div className='container mx-auto px-10 mb-8 max-w-8xl'>
      <Head>
        <title>DevReps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 text-gray-100'>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post, index) => (
            <PostCard post={post.node} key={post.title}/>
          ))}
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>


      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export async function getStaticProps() {
  const posts = (await getPosts()) || []

  return {
    props: { posts }
  }
}
